#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other /bin/sh available, try calling bash
#       explicitly.
#
#   (2) Now that you have a POSIX shell, we load the contents of this file into its
#       memory and start the script from there.
#
#   (3) The actual "gradle" application (in this folder or as part of installation)
#       does appear on the command line except in initialization mode.
#
#   (4) You can use the user's input to set filename paths that may contain spaces.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    app_path=$(readlink "$app_path")
done

APP_HOME=$(cd "${APP_HOME%/*}" && pwd -P) || exit

# Add default JVM options here.
DEFAULT_JVM_OPTS='" "-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != maximum to use that value.
MAX_FD=maximum

warn() {
    if [ "$VERBOSE" = true ]; then
        printf '%s\n' "$*"
    fi
}

die() {
    printf '%s\n' "$*"
    exit 1
}

# OS specific support (must be 'true' or 'false').
case "$(uname)" in
    CYGWIN* | MINGW* | MSYS*)
        cygwin=true
        ;;
    *)
        cygwin=false
        ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ]; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" \n\nPlease set the JAVA_HOME variable in your environment to match the location of your Java installation."
    fi
else
    JAVACMD=java
    command -v java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." \n\nPlease set the JAVA_HOME variable in your environment to match the location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop"; then
    case $MAX_FD in
        (unbounded)
            MAX_FD_LIMIT=unbounded
            ;;
        (*)
            if readlink /proc/$$/fd/1 >/dev/null 2>&1; then
                MAX_FD_LIMIT=$(ulimit -H -n) || MAX_FD_LIMIT=unbounded
            else
                MAX_FD_LIMIT=65536
            fi
            ;;
    esac
    ulimit -n $MAX_FD_LIMIT
fi

if [ "$cygwin" = "true" ]; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    JAVACMD=$(cygpath --mixed "$JAVACMD")
    GRADLE_USER_HOME=$(cygpath --path --mixed "$GRADLE_USER_HOME")
fi

# Now convert the arguments - kludge to limit ourselves to /bin/sh
for arg do
    if
        case $arg in
            (-*)  false ;;
            (*)
                true
                ;;
        esac
    then
        arg=$(printf '%s\n' "$arg" | sed "s/'/'\\\\''/g")
        printf ' %s' "'$arg'"
    else
        printf ' %s' "$arg"
    fi
done <<EOF
$@
EOF
    # xargs treats the newline as a delimiter, so GNU xargs will die when it encounters
    #   a newline character in one of the arguments - let's change IFS temporarily to 
    #   work around this problem.
    #   See a possible solution at: http://permalink.gmane.org/gmane.comp.gnu.utils.help/30392
    IFS="
          " eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS"
        printf '%s' "$@"
    | xargs -0 basename -a |
    grep -E 'java|gradle')"
    exec "$JAVACMD" "$@"
